// Generated by CoffeeScript 1.6.3
chrome.runtime.onMessage.addListener(function(req, sender, msg) {
  var popup;
  if (req.word === 'open') {
    popup = {
      type: 'popup',
      url: 'build/select.html',
      left: 600,
      width: 400,
      height: 600,
      focused: true
    };
    return chrome.windows.create(popup, function(win) {
      return win.alwaysOnTop = true;
    });
  }
});

/*
//@ sourceMappingURL=bg.map
*/
