// Generated by CoffeeScript 1.6.3
(function() {
  var has_open_window, last_window_id, openWindow, popup;

  has_open_window = false;

  last_window_id = void 0;

  popup = {
    type: 'popup',
    url: 'index.html',
    focused: true,
    width: 400
  };

  openWindow = function() {
    return chrome.windows.getCurrent(function(from_win) {
      popup.left = from_win.width - popup.width + from_win.left;
      popup.top = from_win.top;
      popup.height = from_win.height - 24;
      return chrome.tabs.query({
        active: true
      }, function(tabs) {
        return chrome.windows.create(popup, function(win) {
          var tab;
          chrome.windows.update(win.id, {
            drawAttention: true
          });
          last_window_id = win.id;
          tab = tabs[0];
          console.log("tab:", tab);
          return chrome.extension.sendMessage({
            type: "initial",
            tab: tab
          });
        });
      });
    });
  };

  chrome.commands.onCommand.addListener(function(command) {
    if (command === "launch") {
      console.log('going to open a windows');
      console.info('has_open_window', has_open_window);
      console.info('last_window_id', last_window_id);
      if (has_open_window) {
        if (last_window_id != null) {
          return chrome.windows.update(last_window_id, {
            focused: true
          });
        }
      } else {
        openWindow();
        return has_open_window = true;
      }
    }
  });

  chrome.extension.onMessage.addListener(function(req, sender, msg) {
    if (req.word === 'close') {
      console.log('close');
      has_open_window = false;
      return last_window_id = null;
    } else if (req.word === 'log') {
      return console.log('log::', req.data);
    }
  });

  chrome.browserAction.onClicked.addListener(function(tab) {
    return openWindow();
  });

}).call(this);

/*
//@ sourceMappingURL=bg.map
*/
