// Generated by CoffeeScript 1.6.3
document.body.onkeydown = function(event) {
  if (event.keyCode === 192) {
    if (event.ctrlKey) {
      return chrome.extension.sendMessage({
        word: 'open'
      }, function(res) {
        return console.log(res);
      });
    }
  }
};

/*
//@ sourceMappingURL=listen.map
*/
