// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: "./",
    paths: {
      Ractive: "../bower_components/ractive/Ractive",
      cirru: "../bower_components/cirru-parser/src/parser",
      c2m: "../bower_components/cirru-to-mustache/mustache"
    }
  });

  require(["./lib/find"]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
